### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by aqtoo** [RecklessBoon/Macro-Deck-Discord-Plugin#18]
if I try using it, it asks to interface with my discord client via the application, yet seemingly the toggle deafen and mute buttons do not work.

**Comment by DodecaDev-LLC** [comment]
Hey, have you followed the instructions on the README.md page and/or followed the [video tutorial](https://youtu.be/alSlrnzx-M8?si=xmZcjoOZCZbf57ib)?

Do other functions work and can confirm that it is actually connected?

Also, when using Deafen, it can get a little desync'd due to Discord automatically changing the state of Mute as well and the button state not updating until the event message for that is received. Try hitting the deafen button again if it is stuck on. It may have missed that event message somehow.

**Comment by aqtoo** [comment]
Apolgoies for this! Macro Deck simply needed a restart and I got everything up and running, hence why I quickly closed the issue, and thanks for the quick response!
