### ISSUE TITLE
Image Key and the Image Text is inverted

### ISSUE THREAD

**Issue by Benjiiben53** [RecklessBoon/Macro-Deck-Discord-Plugin#4]
Hi, i found a "bug" on your last update on the action "**set rich presence**" there have one problem, the **Large Image Key** and the **Large Image Text** is inverted, same for **Small Image key** and **Small Image Text**

That all for now :)
Have a nice day

**Comment by RecklessBoon** [comment]
thanks Ill take a look when I can!

**Comment by RecklessBoon** [comment]
Hello, I have double checked in the code and performed some tests on my environment. It all works as expected and there is no inversion of the Key/Text on either field. You can reach out on the community Discord if you would like help stepping through the problem more. Otherwise, you can link more supporting information to this issue if you still believe it is a bug to be fixed.
